spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://config-service:8888

  datasource:
    url: jdbc:mysql://localhost:3306/bike
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

    sql:
      init:
        platform: mysql

  logging:
    level:
      root: debug