spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-service:8888

  datasource:
    url: jdbc:mysql://localhost:3306/bike
    username: root
    password: Admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
logging:
  level:
    root: debug